### ISSUE TITLE
"Failed to run flutter pub get"

### ISSUE THREAD

**Issue by Cal-Hagner** [fluttercommunity/import_sorter#14]
**Describe the bug**
When `flutter pub run import_sorter:main` is run, it exits with exit code 127, and fails to run `flutter pub get`. However, when `flutter pub get` is run individually of `flutter pub run import_sorter:main`, it works fine, and running `flutter pub get -v` produces the expected output, all exit codes 0.

**To Reproduce**
I ran `flutter pub run import_sorter:main`. I am using import_sorter 3.0.5, Ubuntu 19.10, Flutter 1.8.0-11.1.pre on channel beta, and Dart 2.9.0-8.2.beta.

**Expected behavior**
I expected the program to run properly, or at the very least, not fail on `flutter pub get`, but rather another step.

**Screenshots**
![image](https://user-images.githubusercontent.com/44558033/82729488-f9b37700-9cc5-11ea-9c2e-56d7f8e965aa.png)
![image](https://user-images.githubusercontent.com/44558033/82729490-fe782b00-9cc5-11ea-8e3a-c57ea5144c63.png)

**Meta Information:**
 - Dart Version:
 - `import_sorter` Version: ^3.0.5
 - Is it a Flutter project? Yes.
 - What version of Flutter are you using (if flutter project): 1.8.0-11.1.pre on channel beta

**Comment by Cal-Hagner** [comment]
This is an interesting exit code, as it signifies that `flutter pub get` does not exist, which doesn't make sense, for, as you can see in the screenshots, `flutter pub get` certainly does exist.

**Comment by Matt-Gleich** [comment]
Are you running this in windows? It might be having the same process error that we had with morse module.

**Comment by Matt-Gleich** [comment]
Yeah just tested it on macOS and works fine for me.
