### ISSUE TITLE
Can generated files be ignored?

### ISSUE THREAD

**Issue by britannio** [fluttercommunity/import_sorter#16]
**Is your feature request related to a problem? Please describe.**
When I run code generation, the sorting and comments for imports are overridden and they aren't very relevant for generated code anyway.

**Describe the solution you'd like**
The option to provide a regular expression like `**/*.g.dart` that skips files matching it.

**Comment by Matt-Gleich** [comment]
This is a great idea! I think that this would be added to the current feature to ignore files based of their exact file name. Thank you!

**Comment by britannio** [comment]
Wow, thanks for such a quick fix!

**Comment by Matt-Gleich** [comment]
Np!  I only had to change like 3 lines so it was an easy fix!
