### ISSUE TITLE
Sort imports without adding comments

### ISSUE THREAD

**Issue by DFelten** [fluttercommunity/import_sorter#20]
Thanks for this package! I've got a little suggestion. 

I like the idea to sort my imports, but I would like to have the comments removed. A flag to sort the imports without adding comments like "Flutter imports:" would be great.

**Comment by Matt-Gleich** [comment]
This is a great idea! I will get to work on this later today and the PR adding this feature will be linked to this issue. Thank you for the great idea!

**Comment by Matt-Gleich** [comment]
Sorry about the lack of work here. Looking into it right now!

**Comment by Matt-Gleich** [comment]
Released! Check the `README.md` for the updated docs!
