### ISSUE TITLE
Exit with non-zero exit code when files were changed

### ISSUE THREAD

**Issue by t-animal** [fluttercommunity/import_sorter#21]
**Is your feature request related to a problem? Please describe.**
In CI pipelines it would be handy to ensure that all imports are sorted. However, this requires checking for changes manually.

**Describe the solution you'd like**
If changes were done to any file, exit with exit code 1, otherwise exit code 0.

**Describe alternatives you've considered**
Checking if files have changed using git.

**Comment by Matt-Gleich** [comment]
Ahh, this is a good idea! As a quick fix for your CI, you can just run the following command after running import_sorter: `git diff --exit-code`

**Comment by Matt-Gleich** [comment]
Released! Check the `README.md` for the updated docs!
