### ISSUE TITLE
Actually sort imports

### ISSUE THREAD

**Issue by t-animal** [fluttercommunity/import_sorter#23]
The import sorter does a great job at **grouping** the imports. This is a huge improvement already. However, it does not actually **sort** the imports. When re-ordering the imports, they stay in the relative order that they were before.

**Describe the solution you'd like**
The import sorter plugin should 1) group imports by origin (dart,flutter,packages,local) and 2) within each group sort the imports alphabetically. For files with longer import lists this makes maintenance and finding files easier.

**Describe alternatives you've considered**
Bascially there is none, except making sure manually that imports are sorted.

**Comment by Matt-Gleich** [comment]
I agree this would be nice.
