### ISSUE TITLE
Add argument to sort some files only?

### ISSUE THREAD

**Issue by crizant** [fluttercommunity/import_sorter#27]
Hi, I would like to use this together with my git hook, and have my changed files sorted only.
It would be great to having a way to sort only a subset of files, instead of sorting all of them.

**Comment by Matt-Gleich** [comment]
You can configure what files to sort right now using the config. Does this not work for you?

https://github.com/fluttercommunity/import_sorter#%EF%B8%8F-config

**Comment by crizant** [comment]
But how to select files with command arguments?
I want to do it In my git hook config files like:
```
sort-imports:
      glob: "*.dart"
      run: flutter pub run import_sorter:main {staged_files} && git add {staged_files}
```

**Comment by Matt-Gleich** [comment]
Is there a reason you don't want them all sorted in this case?

**Comment by crizant** [comment]
Yes, I have hundreds of files in my repository and it makes the process a little bit slower; also there is a lot unnecessary (and unwanted) outputs.

I want all files to be sorted, but only once. Then for every commits I made to my repository, the unchanged files doesn't need to be sorted, right?

**Comment by Matt-Gleich** [comment]
Ahh, I see. This is a good idea! I will look into it and see how easy it would be to do something like this. Any updates I make will be posted in this issue thread.

**Comment by lig** [comment]
@Matt-Gleich basically, it will be great to have this usable with IDEs/editors meaning sorting in a particular file and in a pre-commit hook, ideally, integrated in the pre-commit tool via pre-commit-config.yaml.

**Comment by Matt-Gleich** [comment]
@lig do you think something like this would work well?

```bash
--files=bin/main.dart,lib/hello.dart
```

**Comment by davidlj95** [comment]
> @lig do you think something like this would work well?
> 
> ```bash
> --files=bin/main.dart,lib/hello.dart
> ```

I think just positional arguments would be better to integrate with other tools like `pre-commit`

**Comment by Matt-Gleich** [comment]
So something like this @davidlj95?

```bash
flutter pub run import_sorter:main bin/main.dart lib/hello.dart
```

**Comment by davidlj95** [comment]
> So something like this @davidlj95?
> 
> ```bash
> flutter pub run import_sorter:main bin/main.dart lib/hello.dart
> ```

Yes!! ✨

**Comment by Matt-Gleich** [comment]
This is now in v4.3.0 of import_sorter! You can supply a list of files or a list of regular expressions to only sort certain files! Check the [command line section in the docs](https://github.com/fluttercommunity/import_sorter#-command-line) for more information.

**Comment by davidlj95** [comment]
> This is now in v4.3.0 of import_sorter! You can supply a list of files or a list of regular expressions to only sort certain files! Check the [command line section in the docs](https://github.com/fluttercommunity/import_sorter#-command-line) for more information.

Thanks!! 🌟
