### ISSUE TITLE
Ignored test_driver folder

### ISSUE THREAD

**Issue by vHanda** [fluttercommunity/import_sorter#30]
**Describe the bug**
When running the import sorter, file in a test_driver folder are ignored.

**To Reproduce**
Create at test_driver folder in the root folder and place some dart files over there.

**Expected behavior**
Those files should have their imports sorted.

**Meta Information:**
 - Dart Version: 2.9.2
 - `import_sorter` Version: 4.2.1
 - Is it a Flutter project? Yes
 - What version of Flutter are you using (if flutter project): 1.20.4

**Comment by Matt-Gleich** [comment]
Hey @vHanda I can add this quickly after school. Thanks for letting me know about this!

**Comment by vHanda** [comment]
Wow. Thank you so much for solving this so fast.

I seriously love this package.
