### ISSUE TITLE
Distinguish what files were changed in the output

### ISSUE THREAD

**Issue by lig** [fluttercommunity/import_sorter#36]
**Is your feature request related to a problem? Please describe.**
It is not clear what files were changed from the `import_sorter` output. In fact. all files appear to be changed. I would like to review files that were changed by the tool. This could be especially useful when running `import_sorter` as a `pre-commit` hook.

**Describe the solution you'd like**
I would like to see just an "Ok" for files that were not changed and the current output for those that were.

**Describe alternatives you've considered**
There is none.

**Comment by Matt-Gleich** [comment]
This sounds great! Do you think having the file name be yellow instead of green would work to signify that it was updated?

**Comment by lig** [comment]
> Do you think having the file name be yellow instead of green would work to signify that it wasn't updated?

I guess. However, it is better to avoid relying on color only IMO as there are a lot of cases when color is not available, i.e. command output in an IDE or on CI, custom terminal color schemes, etc.

As for me, as long as the output is distinguishable in plain text the color doesn't really matter that much.

**Comment by Matt-Gleich** [comment]
So it not shows the number of imports actually update in the file out of the total number of imports. See the change log for more info. Thanks for the suggestion!

**Comment by lig** [comment]
@Matt-Gleich looks like this will do it. Thanks!

**Comment by DanMossa** [comment]
@Matt-Gleich 
Would it be possible to pass in an argument to only print a line with sorted is more than 0?
