### ISSUE TITLE
Archiving `import_sorter`

### ISSUE THREAD

**Issue by gleich** [fluttercommunity/import_sorter#63]
Hello everyone. I'm sad to say that today I am going to be archiving import_sorter. Unfortunately I no longer work with dart and flutter anymore and as I go into college I don't have a lot of free time to maintain the project. Anyone is free to fork the code or take over as maintainer but I am going to be archiving the project today. Sorry for any inconveniences this may cause and thank you so much for all the support.

**Comment by vkammerer** [comment]
@gleich is it the right approach to close all issues and PRs? Our team relies a lot on it, we even made it a rule in our CI where a PR with incorrect imports order won't be mergeable.

Instead of archiving the project, could you instead call for another maintainer on the README?

**Comment by gleich** [comment]
yeah that might be the better approach here. I'll reopen the issues and add a maintainer request on the README. Thanks for the suggestion.

**Comment by vkammerer** [comment]
I would be interested in taking over the maintenance of this package.
However, I will not be available for two months, starting December 18th, so I'm not sure that I am the best person to do so right now.

**Comment by gleich** [comment]
That would be amazing! I can lightly maintain it until you get back. I just can't commit in the long run.

**Comment by bartekpacia** [comment]
Thanks for creating and maintaining this nice tool @gleich! Good luck in college :)

**Comment by lig** [comment]
Hey @gleich!

I'm ok with maintaining it myself as well. Anyway, please, do not forget to transfer pub.dev access to a new maintainer.

BTW, there is https://github.com/fluttercommunity which could be a convenient place to keep the project accessible.

In any case, the new maintainer is free to contact me regarding any help desired.

**Comment by lig** [comment]
So, what's next? I think, it would be helpful to create a dev chat (on the Matrix network perhaps) to gather all willing to help to maintain the project and discuss the next steps there.

**Comment by AlmogRnD** [comment]
I would keen to take this over and maintain the package, do you still need someone to do so?

**Comment by vkammerer** [comment]
@AlmogRnD : @gleich added me as a maintainer to the repository a couple months ago. I haven't addressed the currently open issues, but will get to it in the following weeks.

**Comment by AlmogRnD** [comment]
ok

**Comment by pythonhubdev** [comment]
Any updates on the repository it's unmaintained for years @vkammerer

**Comment by pythonhubdev** [comment]
Yes would be happy to contribute as well

**Comment by pythonhubdev** [comment]
I have raised a PR #70 with latest package version and lint rules along with updated example with latest flutter version. Can someone review this and merge?

**Comment by vkammerer** [comment]
First of all, I want to apologise for not having properly maintained the repository this past year. It took quite a long time for me to have access to the repo, and when I finally did, I was back into the daily routine of my job and kept procrastinating..

But it's great to see that there is still interest in the project! We also use it at my company, and I definitely see value in it.

@pythonhubdev I see you've opened a few PRs, I will review them

**Comment by pythonhubdev** [comment]
Thanks @vkammerer

**Comment by SiroDevs** [comment]
Any updates on this, I may want to be a maintainer.
