### ISSUE TITLE
Keep code before imports

### ISSUE THREAD

**Issue by nodinosaur** [fluttercommunity/import_sorter#9]
I just ran the importer and it broke the project.

Reviewing the file that was reported by the analyzer as broken and comparing to GitHub I saw that `library XXXXXX;` had been stripped.

**Comment by Matt-Gleich** [comment]
👋🏼 Hello! Can you please provide the following information? Thanks!

1. What version of `import_sorter` are you using
2. Would you be able to send the file or is it a private project (easier for me to debug)
3. Does the `library` come before the imports?

**Comment by nodinosaur** [comment]
👋Sure:

1. `import_sorter: any` (my understanding is that this implies latest)
2. Flutter SDK reference for you: [animated_icons.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/animated_icons.dart)
3. The `library` keyword does seem to appear above imports, yes.

**Comment by Matt-Gleich** [comment]
Ah, I thought that might be it. At the moment `import_sorter` removes all code above the imports. I was under the impression that there was never any code before imports but I guess not! I will look at fixing it today and you should see available in `2.1.0`. Let me know if have any other questions!

**Comment by Matt-Gleich** [comment]
This is going to be available tonight in version 3.0.0 when I close all the other issues
